# Generated by Django 5.1.2 on 2024-10-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('auto_field', models.AutoField(primary_key=True, serialize=False)),
                ('big_int_field', models.BigIntegerField()),
                ('binary_field', models.BinaryField()),
                ('boolean_field', models.BooleanField()),
                ('char_field', models.CharField(max_length=255)),
                ('date_field', models.DateField()),
                ('datetime_field', models.DateTimeField()),
                ('decimal_field', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email_field', models.EmailField(max_length=254)),
                ('float_field', models.FloatField()),
                ('file_path_field', models.FilePathField(path='/path/to/files/')),
                ('duration_field', models.DurationField()),
                ('image_field', models.ImageField(upload_to='images/')),
                ('generic_ip_address_field', models.GenericIPAddressField()),
                ('integer_field', models.IntegerField()),
                ('json_field', models.JSONField()),
                ('positive_integer_field', models.PositiveIntegerField()),
                ('positive_small_integer_field', models.PositiveSmallIntegerField()),
                ('positive_big_integer_field', models.PositiveBigIntegerField()),
                ('slug_field', models.SlugField()),
                ('small_integer_field', models.SmallIntegerField()),
                ('text_field', models.TextField()),
                ('time_field', models.TimeField()),
                ('url_field', models.URLField()),
                ('uuid_field', models.UUIDField()),
            ],
        ),
    ]
