# Generated by Django 5.1.2 on 2024-10-26 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pracModels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='file_path_field',
        ),
    ]
